### PR TITLE
Use bg luminance to determine background color

### PR DESCRIPTION
**Pull request by juancampa**
While actual bg color support is implemented

### CODE REVIEW

**Comment by juancampa** [comment]
I feel like `IColor.getLuminance` would be better but I'm not sure what's the idiomatic way of doing that in TypeScript

**Comment by Tyriar** [comment]
> I feel like IColor.getLuminance() would be better than IColorManager.getLuminance(color: IColor) but I'm not sure if that's idiomatic in TypeScript

`IColor` is just an interface and instances of it are basically structs without methods, `IColorManager.getLuminance` looks good 👌

**Comment by juancampa** [comment]
Exactly. Having to do `new Color` would be annoying. Makes sense.

**Comment by juancampa** [comment]
@Tyriar, let me know if you need anything changed

**Comment by Tyriar** [comment]
No CI because it's my fork 😄

**Pull request merged**
