### PR TITLE
Add support for modifiers for PageUp / PageDown keys.

### PR DESCRIPTION
**Pull request by markus-oberhumer**
This allows using things like Ctrl+PageUp in terminal applications.

### CODE REVIEW

**Comment by Tyriar** [comment]
@markus-oberhumer do you have an example of an application that utilizes ctrl+page up/down?

**Comment by markus-oberhumer** [comment]
As a simple example, I'm using Ctrl+PageUp/Down to switch buffers in vim.

`$ cat ~/.vimrc`

```
set nocompatible
nmap <C-PageUp>   :prev<cr>
nmap <C-PageDown> :next<cr>
```

And then try running `vim file1.txt file2.txt` in a real xterm.

**Comment by Tyriar** [comment]
@markus-oberhumer could you reopen this PR against the upstream repo https://github.com/sourcelair/xterm.js based off the v3 branch? This fork is only meant for updating from there and doing one off builds for commits so that vscode can take in unreleased changes.

**Comment by markus-oberhumer** [comment]
Ok, I will do that. Closing this pull request.

**Pull request closed without merging**
